### ISSUE TITLE
forgot password page needs work - styling

### ISSUE THREAD

**Issue by Version-LAA** [Version-LAA/techtrek#116]
<img width="1728" alt="Screen Shot 2023-06-11 at 7 23 05 PM" src="https://github.com/Version-LAA/techtrek/assets/53385426/ed6dee22-ea43-4749-b407-43205793c916">

**Comment by Kameronjan** [comment]
added some styling, just need to replace the login and sign up button then we can close this issue 🙌

**Comment by Kameronjan** [comment]
Closing for now since we will not be showing this page during demo.
Will gladly work on this if we decide to take techtrek to the next level
