### ISSUE TITLE
Specialties bug

### ISSUE THREAD

**Issue by Kameronjan** [Version-LAA/techtrek#34]
<img width="1440" alt="Screenshot 2023-05-27 at 12 54 22 AM" src="https://github.com/Version-LAA/techtrek/assets/122124504/f796c581-25a1-47f7-b17f-4409036dcfb8">

We get this error message when clicking on one of the specialties

**Comment by Version-LAA** [comment]
Should be fixed now. There was a merge conflict that I believe was causing the error.

**Comment by Kameronjan** [comment]
Good job! We’re unstoppable 😄
