### ISSUE TITLE
searching on specialty page is broken

### ISSUE THREAD

**Issue by andrewphan1** [Version-LAA/techtrek#83]
When using the search function, we need to look over the loops because when you search for a certain name, the profile appeared multiple times

![Screenshot 2023-06-08 at 8 37 24 PM](https://github.com/Version-LAA/techtrek/assets/28742019/63ee5627-c145-4c09-acc5-83cbabba9727)

**Comment by Kameronjan** [comment]
Resolved by @Version-LAA 
The 🐐
